title: twbarber.com
email: dev@twbarber.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Tyler Barber. Projects, blog, books.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://twbarber.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
  
kramdown:
  input: GFM

remote_theme: twbarber/jekyll-theme-console

plugins:
  - jekyll-feed

style: dark
listen_for_clients_preferred_style: false

footer: '<a href="https://github.com/twbarber">github</a> | <a href="https://www.linkedin.com/in/twbarber/">linkedin</a>'

header_pages:
  - index.md
  - blog/blog.md
  - books/books.md
  - projects/projects.md

include:
  - _covers