title: twbarber.com
email: dev@twbarber.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Tyler Barber
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://twbarber.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: twbarber/jekyll-theme-console

plugins:
  - jekyll-feed

style: dark

header_pages:
  - index.md
  - about.md
  - test.md
