# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               'Tyler Barber'
tagline:             ''
description:         'Test Description.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Tyler Barber
  url:               https://github.com/twbarber
  email:             me@twbarber.com.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate_path: "page:num"
